### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'attach')

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/slate-write#54]
```
react-dom:4 Uncaught TypeError: Cannot read properties of undefined (reading 'attach')
    at Object.eval [as keyMap] (codemirror.js:4:156330)
    at new ul (codemirror.js:4:133292)
    at ul (codemirror.js:4:129471)
    at ul.fromTextArea (codemirror.js:4:168807)
    at eval (index.js:41214:44)
    at Tr (react-dom:4:73687)
    at pl (react-dom:4:93859)
    at eval (react-dom:4:92602)
    at dl (react-dom:4:92667)
    at el (react-dom:4:86419)
    at xn (react-dom:4:32646)
    at pl (react-dom:4:94001)
    at eval (react-dom:4:90457)
    at v (react:4:3374)
    at Array.ce (react:4:5514)
    at eval (echarts-wordcloud.min.js:5:2655)
```

在打了三个 ` ，尝试插入代码块时报错

之后会导致默认编辑模式也进不去，因为 codemirror 崩了

**Comment by king0billy** [comment]
插眼
